language: go
go: 1.13
before_install: sudo apt-get -y install libgl1-mesa-dev xorg-dev libasound2-dev
script:
  - |
    cd /
    go get github.com/rakyll/statik
    cd -
    go generate
    go build .
