os:
  - osx
  - linux
  - windows
language: go
go: 1.16
jobs:
  include:
    - os: linux
      services:
        - xvfb
before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install libgl1-mesa-dev xorg-dev libasound2-dev; fi
script:
  - |
    go build .
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then xvfb-run -a go test .; fi
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then go test .; fi
